export const ACTOR_TYPE_MAP: string[] = [
  "FARMER",
  "PROCESSOR",
  "PACKAGER",
  "DISTRIBUTOR",
  "RETAILER"
]

export const BATCH_STATE_MAP: string[] = [
  "HARVESTED",
  "PROCESSED",
  "PACKAGED",
  "ATDISTRIBUTORS",
  "ATRETAILERS",
  "TOCUSTOMERS",
  "INSTORAGE",
  "INTRANSIT",
  "INPROCESSING"
]